management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "health, metrics, prometheus, info"
  zipkin:
    tracing:
      endpoint: "${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}"

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: youtube-listener
          uri: http://youtube-listener.javagrunt-com.svc.cluster.local
          predicates:
            - Path=/youtube-listener/**
          filters:
            - RewritePath=/youtube-listener/(?<segment>.*), /$\{segment}
        - id: youtube-service
          uri: http://youtube-service.javagrunt-com.svc.cluster.local
          predicates:
            - Path=/youtube-service/**
          filters:
            - RewritePath=/youtube-service/(?<segment>.*), /$\{segment}
        - id: zipkin
          uri: http://openzipkin.javagrunt-com.svc.cluster.local:9411
          predicates:
            - Path=/zipkin/**
        - id: root
          uri: https://javagrunt.github.io
          predicates:
            - Path=/**
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      password: ${REDIS_PASSWORD:}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}