global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'eureka'
    metrics_path: '/actuator/prometheus'
    eureka_sd_configs:
      - server: http://host.docker.internal:8761/eureka
  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']